### ISSUE TITLE
Peer dependency conflict

### ISSUE THREAD

**Issue by frammkor** [archfz/mini-css-themes-plugin#3]
This is exactly the tool I need but I have a peer dependency conflict with PurgeCSS apparently. They both are using different versions of mini-css-extract-plugin.

Is there any way to fix this?

<img width="609" alt="Screenshot 2023-01-23 at 01 09 53" src="https://user-images.githubusercontent.com/54872944/213964445-83eeff15-8710-4aaa-becf-d0ccf0ba39ad.png">

```json
{
  "name": "webpack-css-purge",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "clean": "rm dist/bundle.js",
    "dev": "webpack --mode development",
    "build": "webpack --mode production"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/core": "^7.20.12",
    "@babel/preset-env": "^7.20.2",
    "@fullhuman/postcss-purgecss": "^5.0.0",
    "@vue/compiler-sfc": "^3.2.45",
    "autoprefixer": "^10.4.13",
    "babel-loader": "^9.1.2",
    "css-loader": "^6.7.3",
    "css-minimizer-webpack-plugin": "^4.2.2",
    "html-webpack-plugin": "^5.5.0",
    "mini-css-extract-plugin": "^2.7.2",
    "mini-css-themes-plugin": "^0.2.1",
    "node-sass": "^8.0.0",
    "postcss": "^8.4.21",
    "postcss-loader": "^7.0.2",
    "sass-loader": "^13.2.0",
    "vue-loader": "^17.0.1",
    "vue-style-loader": "^4.1.3",
    "webpack": "^5.75.0",
    "webpack-cli": "^5.0.1"
  },
  "dependencies": {
    "bootstrap": "^4.6",
    "jquery": "^3.6.3",
    "popper.js": "^1.16.1",
    "vue": "^3.2.45"
  }
}
```

**Comment by archfz** [comment]
Working with webpack plugin is truly a walk in the dark forest. The plugin didn't have support till now for webpack 5, there were changes with how webpack and mini css extract works in new changes. Added support in `1.0.0-beta.0` . Please test if it works.

**Comment by frammkor** [comment]
Thanks for that quick response.

I tested it and it is not working, unfortunately. Some of the API have changed and issues have arisen because of it.

Starting in the 'compiler.options.module.rules.forEach' on the index.js file I tracked some things:

![Screenshot 2023-01-25 at 13 49 17](https://user-images.githubusercontent.com/54872944/214625965-832e73d8-9ba1-45e2-814f-d50dec9148bd.png)

**Comment by archfz** [comment]
The deprecation warnings can be ignored. What is actually the issue as I don't see an error in the screenshot from webpack. Did webpack finish successfully and the output was still not generated for the themed version css?

Could you provide a minimal reproducible example. This would mean trying to reproduce using your webpack config / plugin config. Then I could debug the issue.

**Comment by frammkor** [comment]
Sure! I uploaded the repo and forgot to shear it here.

https://github.com/frammkor/webpack-css-purge-theme-test

**Comment by archfz** [comment]
Here is the fix: https://github.com/frammkor/webpack-css-purge-theme-test/pull/1

I have found some additional small bugs in the plugin which I fixed.

But in general you didn't understand the purpose of this plugin. This plugin is meant for projects using css modules. Please read here what these are: https://github.com/css-modules/css-modules . I modified your code to be in such standard, basically the App component loading and App modules styles.

**Comment by frammkor** [comment]
Perfect! Thanks, @archfz. I tried it out today and seems to be working. A few alerts persist still from WEBPACK but now the CSS code is being compiled with no errors.
I will update you if anything else shows up but I can work from here. I appreciate the quick response.

**Comment by archfz** [comment]
Closing. Feel free to add additional details.
